language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.07 PACKAGE=vicinity
  - OCAML_VERSION=4.07 PACKAGE=vicinity-lwt PINS="vicinity:."
  - OCAML_VERSION=4.06 PACKAGE=vicinity
  - OCAML_VERSION=4.06 PACKAGE=vicinity-lwt PINS="vicinity:."
  - OCAML_VERSION=4.05 PACKAGE=vicinity
  - OCAML_VERSION=4.05 PACKAGE=vicinity-lwt PINS="vicinity:."
  - OCAML_VERSION=4.04 PACKAGE=vicinity
  - OCAML_VERSION=4.04 PACKAGE=vicinity-lwt PINS="vicinity:."
  - OCAML_VERSION=4.03 PACKAGE=vicinity
  - OCAML_VERSION=4.03 PACKAGE=vicinity-lwt PINS="vicinity:."
  - OCAML_VERSION=4.02 PACKAGE=vicinity
  - OCAML_VERSION=4.02 PACKAGE=vicinity-lwt PINS="vicinity:."
os:
  - linux
  - osx
